# Generated by Django 3.1.14 on 2022-08-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_month', models.CharField(max_length=200)),
                ('rent_amount', models.PositiveIntegerField()),
                ('bijli_bill', models.PositiveIntegerField()),
                ('other_amount', models.PositiveIntegerField()),
                ('other_commnet', models.CharField(max_length=200)),
            ],
        ),
    ]
