# Generated by Django 4.1 on 2022-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='rent_month',
        ),
        migrations.AddField(
            model_name='rent',
            name='rentmonth',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'Decemeber')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rent',
            name='bijli_bill',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='other_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='other_commnet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rent_amount',
            field=models.FloatField(),
        ),
    ]
