# Generated by Django 4.1 on 2022-08-16 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_rent_rent_month_rent_rentmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rent_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
