# Generated by Django 3.1.14 on 2022-08-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_rent_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='rentmonth',
            field=models.CharField(max_length=30),
        ),
    ]
